// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface Acervo {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description?: string;
  content?: PortableTextBlock[];
  external_url?: string;
  collection_type?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Licenciatura {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  order?: number;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  excerpt?: string;
  content?: PortableTextBlock[];
  duration?: string;
  modality?: string;
  degree_plan_url?: string;
  active?: boolean;
  curriculum?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Maestria {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  excerpt?: string;
  content?: PortableTextBlock[];
  duration?: string;
  modality?: string;
  degree_plan_url?: string;
  active?: boolean;
  order?: number;
  curriculum?: unknown;
  characteristics?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  content?: PortableTextBlock[];
  excerpt?: string;
  fecha_publicacion?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    library_collections: Acervo;
    licenciaturas: Licenciatura;
    maestrias: Maestria;
    pages: Page;
    posts: Post;
  }
}